name = "opencrom"
main = "src/index.js"
compatibility_date = "2026-01-01"

# Global variables (inherited by environments if needed)
[vars]
# Add any global variables here if needed
# EXAMPLE: APP_NAME = "OpenCrom"

[triggers]
crons = ["*/15 * * * *"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "opencrom-db"
database_id = "9ee56922-3e7c-4f45-be5a-9f8b8622329b"

# Preview environment
[env.preview]
# Any preview-specific vars
[env.preview.vars]
# PREVIEW_VAR = "example"

# Production environment
[env.production]
# Any production-specific vars
[env.production.vars]
# PRODUCTION_VAR = "example"
